#!/usr/bin/env python3
"""Rewrite a Payroll IQ pg_dump so it lands in the `payroll_iq` schema.

Source: vgwampgffykiuzsoyevn, schemas `public` + `app_security`.
Target: nubxrrzwcbhgpvvmbioh, schema `payroll_iq`.

    python3 scripts/db/piq-to-schema.py piq-schema.sql piq-schema.payroll_iq.sql

Everything in the dump is fully schema-qualified, so the rewrite is textual — but
NOT a blind `public.` -> `payroll_iq.`. Three things need handling by name:

1. `search_modules` declares `SET search_path TO 'public', 'extensions'` while the
   other 19 functions declare `''`. A blind rewrite leaves it resolving names in
   a schema that no longer holds its tables, and library search silently returns
   nothing. This is the one case the consolidation plan got wrong.
2. All 15 `app_security.*` helpers are Payroll-specific and move to `payroll_iq`.
   `app_security` in the target is reserved for cross-app contracts only
   (`has_app_role`), so nothing app-specific may stay there.
3. `CREATE SCHEMA public` / `CREATE SCHEMA app_security` are dropped; the target
   already has `app_security`, and `payroll_iq` is created explicitly.

The dump is taken with --no-privileges, which is what removes the schema-wide
`REVOKE ... FROM anon` that migration 004 applies. Applied project-wide on a
shared database that would have broken the other app, so do not re-add it.
"""
import re
import sys

# app_security helpers that are Payroll IQ's, not shared. All of them.
PAYROLL_HELPERS = {
    "is_admin", "is_org_member", "is_org_manager", "learner_owns", "owns_attempt",
    "owns_cycle", "owns_plan", "manages_learner", "org_seats_used",
    "assert_org_within_seats", "enforce_seat_capacity", "enforce_org_seat_capacity",
    "organisations_guard_seats", "organisations_guard_billing",
    "users_guard_privileged_columns",
}


def transform(sql: str) -> tuple[str, dict]:
    counts = {}

    # 1. Schema creation. Drop both; create payroll_iq once, up front.
    sql, counts["drop_create_schema"] = re.subn(
        r"^CREATE SCHEMA (?:public|app_security);\n", "", sql, flags=re.M)
    sql, n = re.subn(r"^COMMENT ON SCHEMA (?:public|app_security) IS [^;]+;\n", "", sql, flags=re.M)
    counts["drop_schema_comment"] = n

    # 2. The search_path trap. Do this BEFORE the generic rewrite: afterwards the
    #    quoted 'public' is indistinguishable from any other string literal.
    sql, counts["search_path_fixed"] = re.subn(
        r"SET search_path TO 'public'", "SET search_path TO 'payroll_iq'", sql)
    leftover = re.findall(r"SET search_path TO (?!''|'payroll_iq')[^\n]+", sql)
    if leftover:
        raise SystemExit(f"unhandled search_path declarations: {leftover}")

    # 3. psql meta-commands. pg_dump 17 wraps its output in \restrict /
    #    \unrestrict. `supabase db push` sends SQL straight to the server, which
    #    has no notion of backslash commands, so they must go.
    sql, counts["psql_meta_stripped"] = re.subn(r"(?m)^\\(?:un)?restrict\b[^\n]*\n", "", sql)

    # 4. Qualified references. `public.` only where it is a schema qualifier -
    #    preceded by a non-word character, so `some_public.thing` is untouched.
    sql, counts["public_refs"] = re.subn(r"(?<![\w.])public\.", "payroll_iq.", sql)
    sql, counts["app_security_refs"] = re.subn(r"(?<![\w.])app_security\.", "payroll_iq.", sql)

    # 5. Undo the rewrite for objects the EXTENSION owns rather than the app.
    #    pg_trgm is installed in `public` on the source project and `extensions`
    #    on the target, so step 4 happily renamed `public.gin_trgm_ops` into a
    #    schema that will never contain it. Postgres rejects the index at apply
    #    time, but a rewrite that captured a function instead would have failed
    #    silently at query time.
    pgtrgm = ("gin_trgm_ops|gist_trgm_ops|similarity|show_trgm|word_similarity"
              "|strict_word_similarity|show_limit|set_limit")
    sql, counts["pgtrgm_repointed"] = re.subn(
        rf"payroll_iq\.({pgtrgm})\b", r"extensions.\1", sql)

    header = (
        "-- Generated by scripts/db/piq-to-schema.py. Do not hand-edit.\n"
        "-- Payroll IQ public + app_security, rewritten into payroll_iq.\n"
        "CREATE SCHEMA IF NOT EXISTS payroll_iq;\n\n"
    )
    return header + sql, counts


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src = open(sys.argv[1], encoding="utf-8").read()
    out, counts = transform(src)

    # Post-conditions. A rewrite that silently half-applied is worse than one
    # that failed, so assert rather than report.
    problems = []
    if re.search(r"(?<![\w.])public\.", out):
        problems.append("`public.` still present after rewrite")
    if re.search(r"(?<![\w.])app_security\.", out):
        problems.append("`app_security.` still present after rewrite")
    for name in PAYROLL_HELPERS:
        if f"payroll_iq.{name}" not in out:
            problems.append(f"helper not carried over: {name}")
    if problems:
        for p in problems:
            print("FAIL:", p)
        return 1

    open(sys.argv[2], "w", encoding="utf-8").write(out)
    for k, v in counts.items():
        print(f"  {k:<22} {v}")
    print(f"  {'tables':<22} {len(re.findall(r'^CREATE TABLE payroll_iq[.]', out, re.M))}")
    print(f"  {'functions':<22} {len(re.findall(r'^CREATE FUNCTION payroll_iq[.]', out, re.M))}")
    print(f"  {'policies':<22} {len(re.findall(r'^CREATE POLICY', out, re.M))}")
    print(f"  {'indexes':<22} {len(re.findall(r'^CREATE (?:UNIQUE )?INDEX', out, re.M))}")
    print(f"  {'triggers':<22} {len(re.findall(r'^CREATE TRIGGER', out, re.M))}")
    print(f"  {'domains':<22} {len(re.findall(r'^CREATE DOMAIN', out, re.M))}")
    print(f"  {'views':<22} {len(re.findall(r'^CREATE VIEW', out, re.M))}")
    print(f"wrote {sys.argv[2]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
