#!/usr/bin/env bash
#
# Regenerate supabase/01-schema.sql from the live database.
#
# WHY THIS EXISTS
# The snapshot is the documented rebuild path (README, CLAUDE.md), but nothing
# kept it level with production, and the drift was silent and one-directional:
# on 2026-09-15 it held 150 of 163 tables, and 8 of the missing ones existed
# NOWHERE in the repo while 7 of those were queried by live code. A rebuild
# would have produced an application that compiles and then fails the moment
# anyone opens the newsletter, capability or time-entry surfaces.
#
# A snapshot that must be updated by hand is a snapshot that will be stale, so
# this is that update, made mechanical. Run it whenever the schema changes;
# `scripts/db/check-schema-drift.sh` fails CI when someone forgets.
#
# USAGE
#   APA_DB_PW must be in .env.local (the database password, not an API key).
#   ./scripts/db/regenerate-schema.sh
#
# NOTES ON THE TWO EDITS THIS MAKES, both load-bearing:
#
#  1. `\restrict` / `\unrestrict` are stripped. pg_dump 18 wraps its output in
#     them; they are PSQL meta-commands that psql 17 does not understand and a
#     server cannot execute at all. The README tells operators to run
#     `psql -f`, so leaving them makes the file fail on exactly the machine it
#     is written for.
#
#  2. `CREATE SCHEMA x;` becomes `CREATE SCHEMA IF NOT EXISTS x;`. 00-prereqs
#     creates the same schemas first, and the documented order is prereqs THEN
#     schema — so the bare form errors on step two of the runbook.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/supabase/01-schema.sql"
PGDUMP="${PGDUMP:-/opt/homebrew/opt/libpq/bin/pg_dump}"
REF="${SUPABASE_PROJECT_REF:-nubxrrzwcbhgpvvmbioh}"
HOST="${SUPABASE_DB_HOST:-aws-0-ap-southeast-2.pooler.supabase.com}"
SCHEMAS=(app_security company_os htt payroll_iq)

PW="$(grep -m1 '^APA_DB_PW=' "$ROOT/.env.local" | cut -d= -f2- | tr -d '\r')"
if [[ -z "$PW" ]]; then
  echo "APA_DB_PW not found in .env.local — this needs the DATABASE password," >&2
  echo "not an API key. Supabase dashboard -> Settings -> Database." >&2
  exit 1
fi

args=(--schema-only --no-owner)
for s in "${SCHEMAS[@]}"; do args+=(--schema="$s"); done

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
PGPASSWORD="$PW" "$PGDUMP" -h "$HOST" -p 5432 -U "postgres.$REF" -d postgres "${args[@]}" -f "$tmp"

# Post-conditions BEFORE overwriting: a truncated dump that silently replaced a
# good snapshot would be worse than no script at all.
tables=$(grep -cE '^CREATE TABLE' "$tmp")
policies=$(grep -cE '^CREATE POLICY' "$tmp")
if (( tables < 150 || policies < 300 )); then
  echo "refusing to write: dump looks truncated ($tables tables, $policies policies)" >&2
  exit 1
fi

{
  echo "-- Generated by scripts/db/regenerate-schema.sh. Do not hand-edit."
  echo "-- Snapshot of $REF, schemas: ${SCHEMAS[*]}."
  echo "-- Apply AFTER supabase/00-prereqs.sql (extensions, roles, schemas)."
  echo "--"
  echo "-- Regenerate after any schema change; check-schema-drift.sh guards it."
  echo
  sed -e '/^\\restrict /d' -e '/^\\unrestrict /d' \
      -e 's/^CREATE SCHEMA \([a-z_]*\);/CREATE SCHEMA IF NOT EXISTS \1;/' "$tmp"
} > "$OUT"

echo "wrote $OUT"
echo "  tables:   $tables"
echo "  policies: $policies"
echo "  grants:   $(grep -cE '^GRANT' "$OUT")"
