-- Backfill: map the 72 distinct free-text `industry` values to the fixed
-- 15-category taxonomy in industry_normalized. Raw `industry` is untouched.
-- Matching is lower(trim())-insensitive; guarded so re-running is a no-op and
-- manual corrections (industry_normalized already set) are never overwritten.
-- Run via Supabase MCP execute_sql against project wwchefrgkkxmhlkntufm.

update company_os.companies c
set industry_normalized = m.category,
    updated_at = now()
from (values
  ('acoustic + interior',                                          'Real Estate & Construction'),
  ('advertising services',                                         'Marketing & Media'),
  ('app development',                                              'Technology & Software'),
  ('architectural',                                                'Real Estate & Construction'),
  ('architecture',                                                 'Real Estate & Construction'),
  ('automotive dealership services',                               'Retail & Consumer Goods'),
  ('barbershop',                                                   'Healthcare & Wellness'),
  ('beer',                                                         'Food & Beverage'),
  ('building / home services',                                     'Real Estate & Construction'),
  ('business analysis',                                            'Professional Services'),
  ('business finance and loan brokerage',                          'Financial Services'),
  ('clothes & accessories',                                        'Retail & Consumer Goods'),
  ('coconut manufacturer',                                         'Manufacturing'),
  ('construction',                                                 'Real Estate & Construction'),
  ('consumer goods',                                               'Retail & Consumer Goods'),
  ('craft brewery',                                                'Food & Beverage'),
  ('dental services',                                              'Healthcare & Wellness'),
  ('e-commerce platform',                                          'Technology & Software'),
  ('education',                                                    'Education'),
  ('energy industry insurance and risk management',                'Financial Services'),
  ('esports and gaming entertainment',                             'Marketing & Media'),
  ('executive search & consulting',                                'Professional Services'),
  ('finance',                                                      'Financial Services'),
  ('food & beverage',                                              'Food & Beverage'),
  ('food & beverage - american diner restaurant',                  'Food & Beverage'),
  ('foodservice distribution',                                     'Food & Beverage'),
  ('foodservice industry',                                         'Food & Beverage'),
  ('fund investors',                                               'Financial Services'),
  ('golf club',                                                    'Hospitality & Travel'),
  ('grill & bar',                                                  'Food & Beverage'),
  ('health care',                                                  'Healthcare & Wellness'),
  ('hospitality',                                                  'Hospitality & Travel'),
  ('hospitality and luxury hotels',                                'Hospitality & Travel'),
  ('hospitality & entertainment',                                  'Hospitality & Travel'),
  ('hospitality training & social enterprise',                     'Hospitality & Travel'),
  ('hotel and b&b',                                                'Hospitality & Travel'),
  ('housing / real estate advisory',                               'Real Estate & Construction'),
  ('information services',                                         'Technology & Software'),
  ('insurance and financial services',                             'Financial Services'),
  ('investment',                                                   'Financial Services'),
  ('landscaping services',                                         'Real Estate & Construction'),
  ('legal',                                                        'Legal'),
  ('legal services',                                               'Legal'),
  ('logistics and supply chain.  spirits distribution company',    'Logistics & Supply Chain'),
  ('marketing',                                                    'Marketing & Media'),
  ('media/marketing for cpg brands and back office services',      'Marketing & Media'),
  ('multi-industry corporations',                                  'Other'),
  ('payroll professionals services',                               'Professional Services'),
  ('photography',                                                  'Marketing & Media'),
  ('plumbing & maintenance services',                              'Real Estate & Construction'),
  ('preferred integrated digital iot home solution provider',      'Technology & Software'),
  ('premier production',                                           'Marketing & Media'),
  ('private advisory boards for ceos,',                            'Professional Services'),
  ('professional services',                                        'Professional Services'),
  ('property management / real estate',                            'Real Estate & Construction'),
  ('real estate',                                                  'Real Estate & Construction'),
  ('restaurant and food services',                                 'Food & Beverage'),
  ('retail',                                                       'Retail & Consumer Goods'),
  ('retail health and personal care products (sexual wellness)',   'Retail & Consumer Goods'),
  ('saas',                                                         'Technology & Software'),
  ('sanitary equipment manufacturing',                             'Manufacturing'),
  ('software development',                                         'Technology & Software'),
  ('sports',                                                       'Other'),
  ('steel structure provider',                                     'Manufacturing'),
  ('storage services',                                             'Logistics & Supply Chain'),
  ('sustainable materials & bioplastics',                          'Manufacturing'),
  ('technology',                                                   'Technology & Software'),
  ('travel',                                                       'Hospitality & Travel'),
  ('wellness',                                                     'Healthcare & Wellness'),
  ('wellness and fitness services',                                'Healthcare & Wellness'),
  ('wholesale',                                                    'Retail & Consumer Goods'),
  ('ypo',                                                          'Professional Services')
) as m(raw, category)
where lower(trim(c.industry)) = m.raw
  and c.industry_normalized is null;
