-- Applied 2026-07-11 via Supabase MCP migration `vendors_backfill`.
-- Seed: 23 vendors from the normalized "Suppliers list" spreadsheet
-- (car rentals, travel agencies, conference rooms for the retreat).
insert into company_os.vendors
  (type, name, price_range, address, phone, tax_id, bank_info, primary_contact_name, primary_contact_email, primary_contact_phone, secondary_contact_name, secondary_contact_email, secondary_contact_phone, rating, url, notes)
values
  ('car', 'Thiên Bảo Car', '1,900,000 VND/day (Carnival 7s Signature, VF9 Plus)', null, '0902847524 (Zalo)', null, null, null, null, null, null, null, null, 'Preferred', 'https://www.thienbaocar.com/cac-dong-xe', 'Preferred - variety of options. Time policy: 21:00 - 20:00 next day. Deposit: 20M VND. Free charge <350km for VF; +200k if car taken earlier than 20:00; +~100k if their people deliver or collect the car. Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('car', 'Minh Phuong Saigon', '1,500,000 VND/day (Carnival 7s Signature only - no VinFast)', null, null, null, null, null, null, null, null, null, null, 'Preferred', 'https://minhphuongsaigon.vn/', 'Preferred - cheapest for Carnival. Time policy: 21:00 - 21:00 next day. Deposit: 30M VND. Extra charge for half day; +~100k if their people deliver or collect the car; near driver Vu''s house. Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('car', 'World Car EV', '1,900,000 VND/day (VF9 Plus); 1,400,000 VND/day (VF8 Plus)', null, '0777.61.2222', null, null, null, null, null, null, null, null, 'Preferred (VF8 Plus)', null, 'Preferred for VF8 Plus. Time policy: night time - 24 hours. Deposit: 20M VND. VAT 10%. Free charge 500km/day (+100k if weekend; +10k/km for delivering and receiving cars). Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('car', 'Lux Car Viet', '1,900,000 VND/day (Carnival 7s Signature - no VinFast models)', null, null, null, null, null, null, null, null, null, null, null, 'https://luxcarviet.com/', 'Time policy: 21:00 - 21:00 next day. Deposit: 20M VND. No extra charge if we keep the car a bit longer - flexible and customer-oriented, but vendor sounds a little "bossy" on the phone. Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('car', 'Amazing Xanh', 'VF8 Plus: 1.2M - 1.8M VND/day; 600k/half-day', null, null, null, null, null, null, null, null, null, null, null, 'https://amazingxanh.vn/', 'Cheapest for VF8 but not many options (VF8 or VF3 only). Time policy: 8:00 - 21:00 (same day). Deposit: 2M VND only. Free charge <200km; quote is for travelling inside HCMC only. Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('car', 'Bonbon App', 'Carnival 7s: 1.7M - 2.4M; VF9 Plus: 1.1M - 1.3M; VF8 Plus: 1.5M VND/day', null, null, null, null, null, null, null, null, null, null, null, 'https://www.bonboncar.vn/tim-xe', 'SaaS app connecting individual car owners with customers - cheap, many options, but car quality may depend on the owner. Hourly packages (4/8/12/24 hrs), book 2 hours in advance. Deposit: 500k immediately to keep the slot (non-refundable if we refuse the car on receiving) + 3M on receiving the car; ~500k extra for their team to deliver/return the car to our desired location. Prices exclude VAT (~150-200k VND/day) and possible car delivery/collection fees (200-300k VND). Can issue VAT invoice.'),
  ('tour', 'Vespa Adventures', '$60 to $110 per tour', null, null, null, null, null, null, null, null, null, null, null, 'https://www.vespaadventures.com', null),
  ('travel_agency', 'Datviet', '63,730,800 VND (~$2,405) - Hanoi/Ha Long/Ninh Binh package', null, null, null, null, 'Ms. Lan Anh', null, '1800 6700', null, null, null, null, null, 'VAT included. English-speaking tour guide not yet confirmed. Cheap but not very locally knowledgeable.'),
  ('travel_agency', 'Hanoi Tourist', '71,610,000 VND (~$2,702) - Hanoi/Ha Long/Ninh Binh package', null, null, null, null, 'Ms. Phuong', null, '0965934518', null, null, '0915327429', 'Preferred', null, 'Preferred. VAT included, full package. Local, great knowledge in Hanoi tours, very responsive. Price computed from source formula 2,310,000 VND x 31 pax.'),
  ('travel_agency', 'Viet Thinh Travel', '84,000,000 VND (~$3,170) - Hanoi/Ha Long/Ninh Binh package', null, null, null, null, 'Ms. Tho', null, '0918275133', null, null, null, null, null, 'Expensive.'),
  ('conference_room', 'The Hive Tran Nao', '400k VND/hour -> 3.2M VND/day (last quote)', '(1) 94 Xuân Thủy, Phường An Khánh; (2) 29 Nguyễn Bá Lân, Phường Thảo Điền', null, null, null, null, null, null, null, null, null, null, null, 'Checking availability.'),
  ('conference_room', 'TEC', null, null, null, null, null, null, null, null, null, null, null, null, null, 'Checking quote - will get back to us.'),
  ('conference_room', 'Saigon Coworking Thảo Điền', '600k VND/hour -> 4,800,000 VND/day (including drinks)', null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('conference_room', 'Elite Office', '2M VND/day', '1 Đặng Văn Sâm, Phú Nhuận', null, null, null, null, null, null, null, null, null, null, null, null),
  ('conference_room', 'Dreamplex', '1.4M - 1.6M VND/hour -> 15M VND/day', null, null, null, null, null, null, null, null, null, null, null, null, 'Not available in D2 but available in D1. Same quote as The Kin.'),
  ('conference_room', 'The Kin', '~15M VND/day (same quote as Dreamplex)', null, null, null, null, null, null, null, null, null, null, null, null, null),
  ('conference_room', 'Workflow Thảo Điền', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Not enough space to accommodate - only up to 12 pax.'),
  ('conference_room', 'Office Saigon', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Locations only in Tân Bình and Gò Vấp.'),
  ('conference_room', 'Cocoro', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Does not work on Saturdays.'),
  ('conference_room', 'Regus', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Does not work on Saturdays.'),
  ('conference_room', 'Arental (Aspace office building)', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Does not work on Saturdays.'),
  ('conference_room', 'Inspire Hub', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Does not work on Saturdays.'),
  ('conference_room', 'HQ Songha', null, null, null, null, null, null, null, null, null, null, null, 'Ruled out', null, 'Does not work on Saturdays.');
