-- GENERATED by scripts/data-dictionary/generate.mjs from docs/db/data-dictionary.md.
-- Do not hand-edit: edit the dictionary and regenerate.

comment on table company_os.people is 'One row is: one human the company has ever touched — staff, client contact, candidate who converted, event attendee, AIO participant once the bridge lands. [master · People & org structure | tier 1 spine | active]';
comment on column company_os.people.auth_user_id is 'Login identity, FK to auth.users. Nullable — most people in this table never log in.';
comment on column company_os.people.metadata is 'JSONB escape hatch for experimental attributes; promote to real columns once stable.';

comment on table company_os.companies is 'One row is: one external organization in any relationship with us — prospect, client, learner org (post-bridge), partner. [master · Customers & partners | tier 1 spine | active]';
comment on column company_os.companies.lifecycle_stage is 'The org''s current relationship stage with Edge8; extend values rather than adding boolean flags.';
comment on column company_os.companies.client_types is 'Text array of relationship kinds an org can hold simultaneously.';
comment on column company_os.companies.is_ai_program is 'Whether this org is in an AI program engagement.';
comment on column company_os.companies.owner_id is 'The person accountable for the relationship, FK to people.';

comment on table company_os.team_members is 'One row is: one employment relationship — a person in a seat at one of our legal entities; a person can appear more than once across time. [master · People & org structure | tier 1 spine | active]';
comment on column company_os.team_members.person_id is 'The human behind this employment, FK to people.';

comment on table company_os.deals is 'One row is: one revenue opportunity with one company, moving through one pipeline''s stages. [transactional · Revenue documents | tier 1 spine | active]';
comment on column company_os.deals.amount_cents is 'Deal value in minor units with currency; amount_usd_cents/fx_rate carry the normalized figure.';
comment on column company_os.deals.stage_id is 'Current pipeline stage, FK to pipeline_stages.';
comment on column company_os.deals.handoff_status is 'State of the sales-to-delivery handoff workflow.';
comment on column company_os.deals.referrer_id is 'Person who referred this deal, FK to people — the referral loop is load-bearing.';
comment on column company_os.deals.lost_reason is 'Why a lost deal was lost; filled on close-lost only.';

comment on table htt.pull_requests is 'One row is: one pull request observed in a tracked client or internal repo — the raw evidence of engineering effort. [transactional · Effort & value measurement | tier 1 spine | active]';
comment on column htt.pull_requests.repo_id is 'Source repository, FK to htt.repos.';

comment on table htt.token_entries is 'One row is: one minted human-token record attributed to a person, repo, and client for a span of work. [transactional · Effort & value measurement | tier 1 spine | active]';

comment on table company_os.people_sensitive is 'One row is: one person''s sensitive personal attributes, split from `people` so broad reads can never see them. [master · People & org structure | tier 3 support | active]';

comment on table company_os.candidate_sensitive is 'One row is: one candidate''s sensitive attributes (salary expectation, recruiter-verified and AI-extracted), split from `candidate_profile` so broad ATS reads can never see them. [master · Candidates | tier 3 support | active]';

comment on table company_os.compensation_sensitive is 'One row is: one compensation arrangement for a team member, effective-dated with approver — real pay data. [master · People & org structure | tier 3 support | active]';
comment on column company_os.compensation_sensitive.effective_from is 'Start date of this comp arrangement; history is kept as rows, not overwrites.';
comment on column company_os.compensation_sensitive.is_current is 'Whether this is the active arrangement for the team member.';
comment on column company_os.compensation_sensitive.approved_by is 'Person who approved the change, FK to people.';

comment on table company_os.events is 'One row is: one event we run or speak at — workshop, retreat, talk night — with capacity, dates, and status. [master · Products & offerings | tier 2 stage engine | active]';

comment on table company_os.event_registrations is 'One row is: one person''s registration for one event, from signup through attendance. [transactional · Revenue documents | tier 2 stage engine | active]';

comment on table company_os.marketing_content is 'One row is: one planned or published piece of marketing content (blog, email, social, broadcast) with channel, status, and authored body. [transactional · Marketing & content execution | tier 2 stage engine | active]';
comment on column company_os.marketing_content.body_html is 'Authored email/content HTML; references images by URL.';

comment on table company_os.affiliates is 'One row is: one affiliate partner who can be attributed on deals, orders, and subscriptions. [master · Customers & partners | tier 2 stage engine | active]';

comment on table company_os.lead is 'One row is: one inbound or sourced lead before qualification — the rawest stage of the funnel. [transactional · Pipeline activity | tier 2 stage engine | active]';

comment on table company_os.inquiries is 'One row is: one inbound inquiry from a public form or channel, with routing status. [transactional · Pipeline activity | tier 2 stage engine | active]';

comment on table company_os.interactions is 'One row is: one logged touch with a person or company — call, email, note, meeting reference. [transactional · Pipeline activity | tier 2 stage engine | active]';

comment on table company_os.pipelines is 'One row is: one sales pipeline definition (one exists today). [master · Reference & rules | tier 2 stage engine | active]';

comment on table company_os.pipeline_stages is 'One row is: one stage in one pipeline, ordered. [master · Reference & rules | tier 2 stage engine | active]';

comment on table company_os.tasks is 'One row is: one unit of internal work on a board, in a sprint, or standalone. [transactional · Client delivery & work | tier 2 stage engine | active]';

comment on table company_os.client_backlog_items is 'One row is: one client-visible backlog item on a client roadmap. [transactional · Client delivery & work | tier 2 stage engine | active]';

comment on table company_os.meetings is 'One row is: one meeting or meeting-note record — calendar meetings and folded-in notes distinguished by `source`. [transactional · Client delivery & work | tier 2 stage engine | active]';
comment on column company_os.meetings.source is 'Where this record came from; notes rows carry the folded meeting_notes content. TODO(owner) enumerate: Valid values: [calendar, notes, ...].';

comment on table company_os.sprints is 'One row is: one sprint window for the internal team. [other · Plans & designs | tier 2 stage engine | active]';

comment on table htt.man_hour_entries is 'One row is: one logged span of human hours with a rate, attributed to a person, repo, and client. [transactional · Effort & value measurement | tier 2 stage engine | active]';

comment on table htt.repos is 'One row is: one tracked repository, internal or client-owned. [master · Assets & code | tier 2 stage engine | active]';

comment on table htt.token_allocations is 'One row is: one allotment of tokens to a client engagement — the "allotted" side of burnt/allotted/unburnt. [other · System config & plumbing | tier 2 stage engine | active]';

comment on table htt.client_identities is 'One row is: one mapping from a tracker client to identifying handles (GitHub org, names) used by the sync. [master · Customers & partners | tier 2 stage engine | active]';

comment on table company_os.invoices is 'One row is: one invoice mirrored from QuickBooks — QuickBooks is the system of record; this row is for visibility and joins. [transactional · Revenue documents | tier 2 stage engine | active]';

comment on table company_os.orders is 'One row is: one Stripe checkout order for a product, with fees, tax, FX, and refunds captured. [transactional · Revenue documents | tier 2 stage engine | active]';

comment on table company_os.subscriptions is 'One row is: one Stripe subscription for a person and product. [transactional · Revenue documents | tier 2 stage engine | waiting]';

comment on table company_os.products is 'One row is: one sellable product or ticket tier, Stripe-linked, optionally tied to an event. [master · Products & offerings | tier 2 stage engine | active]';

comment on table company_os.service_lines is 'One row is: one service line the company sells, used to categorize deals and products. [master · Products & offerings | tier 2 stage engine | active]';

comment on table company_os.fx_rates is 'One row is: one currency''s current rate to USD. [master · Reference & rules | tier 2 stage engine | active]';

comment on table company_os.positions is 'One row is: one job position definition in the org structure. [master · People & org structure | tier 3 support | active]';

comment on table company_os.departments is 'One row is: one department in the org structure. [master · People & org structure | tier 3 support | active]';

comment on table company_os.staff_assignments is 'One row is: one assignment of a team member to a client, project, or internal function for a period. [master · People & org structure | tier 3 support | active]';

comment on table company_os.person_qualifications is 'One row is: one durable qualification or certification held by a person. [master · People & org structure | tier 3 support | active]';

comment on table company_os.legal_entities is 'One row is: one of our legal entities (country, base currency, tax id). [master · People & org structure | tier 3 support | active]';

comment on table company_os.company_profile is 'One row is: one block of our own company profile content. [master · People & org structure | tier 3 support | active]';

comment on table company_os.core_values is 'One row is: one company core value. [master · People & org structure | tier 3 support | active]';

comment on table company_os.coaching_profiles is 'One row is: one team member''s coaching profile — the standing context a coach needs. [master · People & org structure | tier 3 support | active]';

comment on table company_os.coaching_ocean_profiles is 'One row is: one person''s OCEAN personality assessment result. [master · People & org structure | tier 3 support | active]';

comment on table company_os.person_companies is 'One row is: one person-to-company relationship (role, primary contact flags) — the join that makes contacts work. [master · Customers & partners | tier 3 support | active]';

comment on table company_os.candidates is 'One row is: one candidate in the recruiting funnel (person-like entity; becomes a `people` row on hire). [master · Candidates | tier 3 support | active]';

comment on table company_os.candidate_profile is 'One row is: one candidate''s extended profile (resume-derived, broadly readable — nothing sensitive). [master · Candidates | tier 3 support | active]';

comment on table company_os.vendors is 'One row is: one vendor or supplier with contact, bank, and tax details. [master · Vendors | tier 3 support | active]';

comment on table company_os.ai_programs is 'One row is: one AI program engagement definition for a client. [master · Products & offerings | tier 3 support | active]';

comment on table company_os.talks is 'One row is: one talk in our speaking catalog. [master · Products & offerings | tier 3 support | active]';

comment on table company_os.brands is 'One row is: one brand we operate under. [master · Products & offerings | tier 3 support | active]';

comment on table company_os.brand_profiles is 'One row is: one brand''s extended profile (voice, style, positioning) used by content tooling. [master · Products & offerings | tier 3 support | active]';

comment on table company_os.equipment is 'One row is: one physical asset we own (laptop, monitor, device). [master · Assets & code | tier 3 support | active]';

comment on table company_os.company_github_orgs is 'One row is: one GitHub organization mapped to a client company. [master · Assets & code | tier 3 support | active]';

comment on table company_os.person_git_emails is 'One row is: one git author email mapped to a person, for PR attribution. [master · Assets & code | tier 3 support | active]';

comment on table company_os.leave_policies is 'One row is: one leave policy (entitlement rules) applied to team members. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.holidays is 'One row is: one public holiday relevant to leave calculation. [master · Reference & rules | tier 3 support | waiting]';

comment on table company_os.boards is 'One row is: one work board (kanban) definition. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.board_columns is 'One row is: one column on one board, ordered. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.board_members is 'One row is: one person''s membership on one board. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.surveys is 'One row is: one survey definition. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.survey_fields is 'One row is: one question or field on one survey. [master · Reference & rules | tier 3 support | active]';

comment on table company_os.tags is 'One row is: one tag label (part of a generic tagging system that was never adopted). [master · Reference & rules | tier 3 support | hold]';

comment on table company_os.taggables is 'One row is: one tag-to-record attachment (polymorphic). [master · Reference & rules | tier 3 support | hold]';

comment on table company_os.requisition_loop_steps is 'One row is: one step in a requisition''s interview loop plan. [master · Reference & rules | tier 3 support | hold]';

comment on table company_os.event_pnl_lines is 'One row is: one revenue or cost line on one event''s P&L. [transactional · Revenue documents | tier 3 support | active]';

comment on table company_os.token_purchases is 'One row is: one purchase of human tokens by a client (the token economy''s revenue record). [transactional · Revenue documents | tier 3 support | waiting]';

comment on table company_os.affiliate_commissions is 'One row is: one commission earned by an affiliate on an attributed sale. [transactional · Revenue documents | tier 3 support | active]';

comment on table company_os.affiliate_payouts is 'One row is: one payout of accumulated commissions to an affiliate. [transactional · Revenue documents | tier 3 support | waiting]';

comment on table company_os.call_transcripts is 'One row is: one call or meeting transcript, linked to its meeting or deal context. [transactional · Pipeline activity | tier 3 support | active]';

comment on table company_os.call_scorecards is 'One row is: one scored review of one call against the sales rubric. [transactional · Pipeline activity | tier 3 support | active]';

comment on table company_os.marketing_campaigns is 'One row is: one marketing campaign grouping content and email sends. [transactional · Marketing & content execution | tier 3 support | active]';

comment on table company_os.email_campaigns is 'One row is: one email campaign (broadcast) definition and send state. [transactional · Marketing & content execution | tier 3 support | active]';

comment on table company_os.email_campaign_recipients is 'One row is: one recipient of one email campaign send. [transactional · Marketing & content execution | tier 3 support | active]';

comment on table company_os.email_events is 'One row is: one email engagement event (delivery, open, click) from the send provider. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.marketing_asset_images is 'One row is: one image in the marketing image library, keyed to a content entry (`entry_id`). [transactional · Marketing & content execution | tier 3 support | active]';

comment on table company_os.marketing_pillars is 'One row is: one marketing pillar for categorizing content. [transactional · Marketing & content execution | tier 3 support | hold]';

comment on table company_os.task_comments is 'One row is: one comment on one task. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.issues is 'One row is: one tracked issue or bug in internal work. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.meeting_participants is 'One row is: one person''s participation in one meeting. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.meeting_associations is 'One row is: one polymorphic link stating what a meeting is about — (meeting_id, entity_type, entity_id) to a deal, company, or project. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.meeting_action_items is 'One row is: one action item captured from a meeting. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.bookings is 'One row is: one external booking made against an availability block. [transactional · Client delivery & work | tier 3 support | active]';

comment on table company_os.expenses is 'One row is: one expense mirrored from QuickBooks — QuickBooks is the system of record. [transactional · Spend | tier 3 support | active]';

comment on table company_os.contractor_payments is 'One row is: one monthly payment decision for a contractor (hours, amount, status). [transactional · Spend | tier 3 support | waiting]';

comment on table company_os.contractor_work_requests is 'One row is: one request for contractor work with scope and rate. [transactional · Spend | tier 3 support | active]';

comment on table company_os.contractor_work_events is 'One row is: one event in a contractor work request''s lifecycle. [transactional · Spend | tier 3 support | active]';

comment on table company_os.equipment_assignments is 'One row is: one assignment of one asset to one person for a period. [transactional · Spend | tier 3 support | active]';

comment on table company_os.equipment_requests is 'One row is: one request for equipment by a team member. [transactional · Spend | tier 3 support | active]';

comment on table company_os.time_off is 'One row is: one leave request with type, dates, and approval state. [transactional · People operations | tier 3 support | active]';

comment on table company_os.leave_adjustments is 'One row is: one manual adjustment to a person''s leave balance. [transactional · People operations | tier 3 support | active]';

comment on table company_os.applications is 'One row is: one candidate''s application to one requisition, through the funnel. [transactional · People operations | tier 3 support | active]';

comment on table company_os.application_stages is 'One row is: one stage instance in one application''s funnel. [transactional · People operations | tier 3 support | active]';

comment on table company_os.job_requisitions is 'One row is: one open or closed hiring requisition. [transactional · People operations | tier 3 support | active]';

comment on table company_os.interviews is 'One row is: one scheduled interview for one application. [transactional · People operations | tier 3 support | active]';

comment on table company_os.interview_interviewers is 'One row is: one interviewer on one interview. [transactional · People operations | tier 3 support | active]';

comment on table company_os.interview_scorecards is 'One row is: one interviewer''s scorecard for one interview. [transactional · People operations | tier 3 support | active]';

comment on table company_os.scorecard_scores is 'One row is: one dimension score on one scorecard. [transactional · People operations | tier 3 support | active]';

comment on table company_os.offers is 'One row is: one formal offer extended to a candidate. [transactional · People operations | tier 3 support | waiting]';

comment on table company_os.onboarding_plans is 'One row is: one onboarding plan for one new team member. [transactional · People operations | tier 3 support | active]';

comment on table company_os.onboarding_tasks is 'One row is: one task inside one onboarding plan. [transactional · People operations | tier 3 support | active]';

comment on table company_os.performance_reviews is 'One row is: one performance review record for one team member in one cycle. [transactional · People operations | tier 3 support | active]';

comment on table company_os.survey_responses is 'One row is: one person''s response session to one survey. [transactional · People operations | tier 3 support | active]';

comment on table company_os.survey_answers is 'One row is: one answer to one field within one response. [transactional · People operations | tier 3 support | active]';

comment on table company_os.goals is 'One row is: one quarterly FAST goal for a team member, laddered to the Eight Edges tree, with member-authored measures. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_goal_comments is 'One row is: one comment on one FAST goal. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_checkins is 'One row is: one coaching check-in record. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_commitments is 'One row is: one commitment made in coaching, tracked to completion. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_context is 'One row is: one standing context note for one person''s coaching. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_one_on_ones is 'One row is: one coaching one-on-one session record. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_priorities is 'One row is: one current priority for one person in coaching. [transactional · People operations | tier 3 support | active]';

comment on table company_os.coaching_talking_points is 'One row is: one talking point queued for one person''s next one-on-one. [transactional · People operations | tier 3 support | active]';

comment on table company_os.strategies is 'One row is: one company strategy document record. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.objectives is 'One row is: one company objective in the OKR tree. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.key_results is 'One row is: one measurable key result under one objective. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.client_roadmap_groups is 'One row is: one grouping on one client''s roadmap. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.client_roadmap_overview is 'One row is: one client roadmap''s overview block. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.program_plans is 'One row is: one AI program''s plan document record. [other · Plans & designs | tier 3 support | active]';

comment on table htt.project_goals is 'One row is: one goal set for a tracked project in the token tracker. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.event_agenda_blocks is 'One row is: one agenda block within one event''s schedule. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.event_agenda_staff is 'One row is: one staff assignment to one agenda block. [other · Plans & designs | tier 3 support | hold]';

comment on table company_os.event_talks is 'One row is: one link between an event and a talk on its program. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.ideas is 'One row is: one captured idea in the R&D funnel. [other · Plans & designs | tier 3 support | active]';

comment on table company_os.documents is 'One row is: one stored document reference (file metadata, not the file itself). [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.company_information is 'One row is: one general company reference fact (slug, title, category, body, tags) surfaced to the /team assistant. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.books is 'One row is: one book in the publishing effort. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.book_chapters is 'One row is: one chapter of one book. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.program_documents is 'One row is: one document attached to an AI program. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.gallery_photos is 'One row is: one photo in the company gallery. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.gallery_photo_people is 'One row is: one person tagged in one gallery photo. [other · Content & knowledge | tier 3 support | active]';

comment on table company_os.audit_log is 'One row is: one audited admin action (who did what to which record). [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.portal_assume_sessions is 'One row is: one assume-identity session by an admin in the portal. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.application_stage_log is 'One row is: one logged stage transition of one application. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.task_stage_log is 'One row is: one logged stage move of one task. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.lifecycle_transitions is 'One row is: one logged lifecycle change of a person (candidate to hire, active to alumni). [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.kr_logs is 'One row is: one progress log entry on one key result. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table htt.sync_runs is 'One row is: one run of the nightly GitHub sync with its outcome. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.sync_packets is 'One row is: one integration sync packet record. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.assistant_conversations is 'One row is: one conversation session with an in-app AI assistant. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.dayoff_snapshot is 'One row is: one snapshotted leave-balance state for one person on one date — derived, rebuildable. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.coaching_trends is 'One row is: one derived trend summary over coaching data — rebuildable. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.idea_trend_reports is 'One row is: one derived trend report over ideas — rebuildable. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table htt.project_summaries is 'One row is: one generated summary of a tracked project — rebuildable. [other · Logs, audit & telemetry | tier 3 support | active]';

comment on table company_os.qbo_connection is 'One row is: one QuickBooks OAuth connection with live access and refresh tokens. [other · System config & plumbing | tier 3 support | active]';

comment on table company_os.integration_sources is 'One row is: one configured external integration source. [other · System config & plumbing | tier 3 support | active]';

comment on table company_os.admins is 'One row is: one admin user of the portal. [other · System config & plumbing | tier 3 support | active]';

comment on table company_os.portal_members is 'One row is: one person''s membership and role in the portal. [other · System config & plumbing | tier 3 support | active]';

comment on table company_os.availability_blocks is 'One row is: one recurring availability window offered for external booking. [other · System config & plumbing | tier 3 support | active]';
